import * as assert from 'assert';
import { SimulationRunCoordinator } from '../workbench/simulationRunCoordinator';
const coordinator = new SimulationRunCoordinator();
const task = { kind: 'st' as const, uri: 'file:///a.st' };
const tb = { kind: 'testbench' as const, uri: 'file:///tb.sv', module: 'tb' };
let cancelled = 0;
const first = coordinator.acquire(task, () => cancelled++);
assert.throws(() => coordinator.acquire(tb, () => {}), /already running/);
assert.strictEqual(coordinator.cancel(tb), false);
assert.strictEqual(cancelled, 0);
assert.strictEqual(coordinator.cancel(task), true);
assert.strictEqual(cancelled, 1);
assert.throws(() => coordinator.acquire(tb, () => {}), /already running/);
first.release();
const second = coordinator.acquire(tb, () => cancelled++);
first.release();
assert.deepStrictEqual(coordinator.active, tb);
assert.strictEqual(coordinator.cancel({ ...tb, module: 'other' }), false);
second.release(); assert.strictEqual(coordinator.active, undefined);
console.log('Simulation run coordinator tests passed');
