import assert from 'node:assert/strict';
import { createSimulationTask } from '@veriflow/hdl-runtime/simulationTask';
import { applyTaskEdit } from '../simulationTask/taskAuthoring';
import { projectSimulationTask, taskModuleKey } from '../simulationTask/taskProjection';
const modules = [{ source: 'dut.v', module: 'dut', ports: [{ name: 'clk', direction: 'input' as const, width: 1 }] }];
let task = createSimulationTask('demo.st');
task.instances.push({ id: 'clock', preset: { kind: 'clock', frequencyMHz: 100, initial: 0 } });
task = applyTaskEdit(task, modules, { type: 'addInstance', instance: { name: 'u_dut', module: 'dut', definitionKey: taskModuleKey('dut.v', 'dut') } });
assert.deepEqual(task.instances[1], { id: 'u_dut', source: { kind: 'hdl', path: 'dut.v', module: 'dut' }, parameters: {} });
task = applyTaskEdit(task, modules, { type: 'connect', source: { kind: 'instance', instance: 'clock', port: 'clk' }, target: { kind: 'instance', instance: 'u_dut', port: 'clk' } });
assert.equal(task.connections.length, 1);
task = applyTaskEdit(task, modules, { type: 'renameInstance', name: 'clock', nextName: 'clk_source' });
assert.equal(task.instances[0].id, 'clk_source');
assert.ok(task.connections[0].endpoints.some(p => p.kind === 'instance' && p.instance === 'clk_source'));
assert.ok('preset' in task.instances[0]);
task = applyTaskEdit(task, modules, { type: 'addLogic', logic: { name: 'one', operation: 'constant', width: 1, expression: "1'b1" } });
assert.equal(task.logic.length, 1);
assert.equal(projectSimulationTask(task, modules, 'file:///demo.st').projection.design.module, 'demo_tb');
assert.throws(() => applyTaskEdit(task, modules, { type: 'addPort', port: { name: 'external', direction: 'input', width: 1 } }), /top-level/);
task = applyTaskEdit(task, modules, { type: 'removeInstance', name: 'clk_source' });
assert.equal(task.instances.length, 1);
assert.ok(!task.connections.some(c => c.endpoints.some(p => p.kind === 'instance' && p.instance === 'clk_source')));
console.log('ST uses AD graph editing while preserving source and preset identities');
