import * as assert from 'assert';

// Removing task isolation or run snapshots must fail these behavior checks.
const { WorkflowState } = require('../workflowState');
const state = new WorkflowState();
const dut = { definitionKey: 'dut', name: 'soc', uri: 'file:///soc.v' };
const entry = { definitionKey: 'tb', name: 'tb_soc', uri: 'file:///tb.v' };
state.setDesign(dut);
const first = state.addTask('smoke', entry, dut, { simulator: 'builtin' });
const run = state.beginRun({ top: entry.name, files: { '/soc.v': 'hash1' }, settings: 'settings1' });
state.finishRun(run.id, 'completed', { log: 'run one', wavePath: '/runs/one.vcd' });
const second = state.addTask('reset', { ...entry, definitionKey: 'tb2', name: 'tb_reset' }, dut, {});
assert.notStrictEqual(first.id, second.id);
assert.strictEqual(state.design.name, 'soc');
assert.strictEqual(state.activeTask.entry.name, 'tb_reset');
assert.strictEqual(state.latestRun.taskName, 'smoke');
assert.strictEqual(state.latestRun.top, 'tb_soc');
assert.strictEqual(state.latestRun.wavePath, '/runs/one.vcd');
state.selectTask(first.id);
state.updateTask(first.id, { name: 'renamed smoke', settings: { simulator: 'builtin' } });
assert.strictEqual(state.latestRun.outdated, false, 'renaming or retaining settings does not change simulation inputs');
assert.strictEqual(state.latestRun.taskName, 'smoke', 'run retains its original task name');
state.markFileChanged('/soc.v', 'hash2');
assert.strictEqual(state.latestRun.outdated, true);
assert.strictEqual(state.latestRun.status, 'completed');
assert.strictEqual(state.latestRun.log, 'run one');
const restored = new WorkflowState(JSON.parse(JSON.stringify(state.serialize())));
assert.strictEqual(restored.activeTask.id, first.id);
assert.strictEqual(restored.design.name, 'soc');
assert.strictEqual(restored.latestRun.outdated, true);
const cancelled = restored.beginRun({ top: entry.name, files: {}, settings: 'settings1' });
restored.finishRun(cancelled.id, 'cancelled', { log: 'cancelled' });
assert.strictEqual(restored.latestRun.wavePath, undefined);
assert.strictEqual(restored.latestRun.status, 'cancelled');
assert.strictEqual(restored.finishRun(run.id, 'failed', {}), false, 'old completion must not replace a newer run');
const interrupted = new WorkflowState(restored.serialize());
interrupted.beginRun({ top: entry.name, files: {}, settings: 'x' });
assert.strictEqual(new WorkflowState(interrupted.serialize()).latestRun.status, 'cancelled');
assert.doesNotThrow(() => new WorkflowState({ version: 1, tasks: [null, {}], latestRun: { status: 'running' } }));
console.log('Workflow state tests passed');
